package com.hp.schemas.sm._7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-02T19:09:45.489+03:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://schemas.hp.com/SM/7", name = "MHintegration")
@XmlSeeAlso({ObjectFactory.class, com.hp.schemas.sm._7.common.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MHintegration {

    @WebMethod(operationName = "RetrieveMegaHelp", action = "Retrieve")
    @WebResult(name = "RetrieveMegaHelpResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveMegaHelpResponse")
    public RetrieveMegaHelpResponse retrieveMegaHelp(

        @WebParam(partName = "RetrieveMegaHelpRequest", name = "RetrieveMegaHelpRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        RetrieveMegaHelpRequest retrieveMegaHelpRequest
    );

    @WebMethod(operationName = "RetrieveMegaHelpKeysList", action = "RetrieveKeysList")
    @WebResult(name = "RetrieveMegaHelpKeysListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveMegaHelpKeysListResponse")
    public RetrieveMegaHelpKeysListResponse retrieveMegaHelpKeysList(

        @WebParam(partName = "RetrieveMegaHelpKeysListRequest", name = "RetrieveMegaHelpKeysListRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        RetrieveMegaHelpKeysListRequest retrieveMegaHelpKeysListRequest
    );

    @WebMethod(operationName = "RetrieveMegaHelpList", action = "RetrieveList")
    @WebResult(name = "RetrieveMegaHelpListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveMegaHelpListResponse")
    public RetrieveMegaHelpListResponse retrieveMegaHelpList(

        @WebParam(partName = "RetrieveMegaHelpListRequest", name = "RetrieveMegaHelpListRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        RetrieveMegaHelpListRequest retrieveMegaHelpListRequest
    );

    @WebMethod(operationName = "CreateMegaHelp", action = "Create")
    @WebResult(name = "CreateMegaHelpResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CreateMegaHelpResponse")
    public CreateMegaHelpResponse createMegaHelp(

        @WebParam(partName = "CreateMegaHelpRequest", name = "CreateMegaHelpRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        CreateMegaHelpRequest createMegaHelpRequest
    );
}
